project: movie_streaming_demo
spark_cluster: local[*]            # or "databricks", "emr", "snowflake"

offline_store:
  type: parquet
  location: data/feathr_offline

online_store:
  type: redis
  host: redis
  port: 6379

registry:
  type: file
  path: .feathr/registry.db
